### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by freespeechsocial** [rifatrakib/php-seach-engine-and-crawler#1]
I dont see a database in your files? This needs a database to work correct?

**Comment by rifatrakib** [comment]
Of course, database size is too big to be uploaded in GitHub

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: freespeechsocial ***@***.***>
Sent: Thursday, April 14, 2022 8:21:38 AM
To: rifatrakib/php-seach-engine-and-crawler ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rifatrakib/php-seach-engine-and-crawler] Database (Issue #1)


I dont see a database in your files? This needs a database to work correct?

**Comment by rifatrakib** [comment]
Of course, database size is too big to be uploaded on GitHub.

**Comment by freespeechsocial** [comment]
So how do I get it? Script wont work without it right?

**Comment by rifatrakib** [comment]
It's not a public search engine, and also not a deployed one. This was something I did a few years ago as a demo school project. I just transferred it from my other account to here yesterday. You need to create a database and necessary tables locally, connect the database via `config.php`, and then run `crawl.php` to populate the database with data downloaded by the crawler.
